import { randomBytes } from 'node:crypto';

export type Variant = 'default' | 'decorations' | 'required' | 'notice' | 'duplicate-form';
export type Values = { orderNumber: string; purchaseDate: string; category: string; contactMethod: string; consent: boolean };
export const categories = ['가전', '생활', '디지털'];
export const contactMethods = ['접수 내역에서 확인', '알림 받지 않음'];
export const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export const noticeFor = (variant: Variant): string => variant === 'notice'
  ? '2026년 9월 구매 건만 신청할 수 있습니다. 신청 기한은 2026년 10월 5일 오후 6시입니다. 확인 후 시연 포인트 3,000점을 제공합니다. 주문당 한 번만 신청할 수 있으며 취소·반품 주문은 제외됩니다. 입력한 주문 정보는 접수 확인을 위해 이 시연 서비스에 저장됩니다. 실제 포인트 지급은 없습니다.'
  : '2026년 9월 구매 건만 신청할 수 있습니다. 신청 기한은 2026년 10월 7일 오후 6시입니다. 확인 후 시연 포인트 5,000점을 제공합니다. 주문당 한 번만 신청할 수 있으며 취소·반품 주문은 제외됩니다. 입력한 주문 정보는 접수 확인을 위해 이 시연 서비스에 저장됩니다. 실제 포인트 지급은 없습니다.';
export const hidden = (name: string, value: string): string => `<input type="hidden" name="${escape(name)}" value="${escape(value)}">`;
export const notice = (variant: Variant): string => `<section class="notice" aria-labelledby="important-notice"><h2 id="important-notice">신청 전 꼭 확인해 주세요</h2><p>${noticeFor(variant)}</p></section>`;

export function layout(title: string, content: string, csrf: string, loggedIn: boolean, variant: Variant): string {
  const links = [['/', '홈'], ['/apply', '구매 혜택 신청'], ['/history', '접수 내역'], ['/guide', '이용 안내'], ['/stores', '매장 안내']];
  if (variant === 'decorations') links.reverse();
  const account = loggedIn ? `<span>시연 회원님</span><form method="post" action="/logout">${hidden('csrf', csrf)}<button class="quiet" type="submit">로그아웃</button></form>` : '<a href="/login">로그인</a>';
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · 온담 혜택</title><link rel="stylesheet" href="/assets/site.css"></head>
  <body><a class="skip" href="#main">본문 바로가기</a><header>
  <div class="util"><div class="util-inner"><span class="demo-badge">시연용 합성 서비스</span><span class="util-note">FLECTO 시연을 위해 만든 가상 포털입니다. 실제 기관·기업·회원 정보와 관련이 없습니다.</span><span class="util-links"><a href="/guide">처음 오셨나요</a><a href="/stores">운영시간</a><a href="/history">내 접수 조회</a></span><div class="account">${account}</div></div></div>
  <div class="header-inner"><a class="brand" href="/">온담<span>구매의 기쁨을 한 번 더</span></a><span class="brand-sub">혜택 통합 포털 <small>DEMO</small></span>
  <table class="head-status"><caption>포털 운영 정보</caption><tbody><tr><th scope="row">접수 방식</th><td>온라인 (시연)</td><th scope="row">운영시간</th><td>월–토 10:00–18:00</td></tr><tr><th scope="row">처리 단계</th><td>작성 → 검토 → 제출</td><th scope="row">휴무일</th><td>일요일·공휴일</td></tr></tbody></table></div>
  <nav aria-label="주 메뉴">${links.map(([href, text]) => `<a href="${href}">${text}</a>`).join('')}</nav>
  <div class="gnb-sub"><div class="gnb-sub-inner"><span class="gnb-group"><b>신청</b><a href="/apply">온라인 신청서 작성</a></span><span class="gnb-group"><b>조회</b><a href="/history">접수번호 확인</a></span><span class="gnb-group"><b>안내</b><a href="/guide">신청 절차</a><a href="/guide">시연 주문번호 범위</a><a href="/guide">자주 묻는 질문</a></span><span class="gnb-group"><b>매장</b><a href="/stores">운영시간·휴무일</a><a href="/stores">시연점 위치</a></span><span class="gnb-group"><b>포털</b><a href="/">포털 첫 화면</a></span></div></div></header>
  <aside class="lnb" aria-label="혜택 서비스 메뉴"><h2>혜택 서비스</h2><ul class="lnb-list"><li><a href="/apply">혜택 신청서</a></li><li><a href="/history">내 신청 현황</a></li><li><a href="/guide">처음 이용 안내</a></li><li><a href="/stores">가상 매장 찾기</a></li><li><a href="/">서비스 전체 보기</a></li></ul>
  <h2>고객 지원</h2><table class="side-table"><tbody><tr><th scope="row">운영</th><td>월–토<br>10:00–18:00</td></tr><tr><th scope="row">휴무</th><td>일요일·공휴일</td></tr><tr><th scope="row">문의</th><td>이용 안내 참고</td></tr></tbody></table>
  <h2>분류별 혜택</h2><table class="side-table"><thead><tr><th scope="col">분류</th><th scope="col">대상 예시</th></tr></thead><tbody><tr><td>가전</td><td>주방·계절 가전</td></tr><tr><td>생활</td><td>생활용품·잡화</td></tr><tr><td>디지털</td><td>휴대기기·주변기기</td></tr></tbody></table>
  <p class="side-foot">모든 주문·매장·포인트는 시연용 합성 데이터입니다.</p></aside>
  <main id="main" tabindex="-1" class="${variant === 'decorations' ? `season-${randomBytes(4).toString('hex')}` : 'content'}"><p class="loc"><a href="/">홈</a> <span aria-hidden="true">›</span> 혜택 서비스 <span aria-hidden="true">›</span> <strong>${escape(title)}</strong></p>${content}</main>
  <footer><div class="foot-links"><a href="/guide">이용 방법 보기</a><a href="/stores">매장 운영 안내</a><a href="/history">접수 내역 조회</a><a href="/apply">혜택 신청 바로가기</a></div><strong>온담 혜택</strong><p>합성 주문으로 체험하는 독립 시연 서비스입니다. 실제 구매 정보는 입력하지 마세요.</p><p class="foot-meta">가상도시 온담로 100 (시연 주소) · 온담 혜택 시연팀 · 이 화면은 실제 공공·민간 서비스를 대신하지 않습니다.</p></footer></body></html>`;
}

export function loginForm(csrf: string, error = ''): string {
  return `<div class="intro"><h1>반갑습니다</h1><p>로그인하고 구매 혜택을 신청해 보세요.</p></div>${error ? `<div role="alert" class="error">${escape(error)}</div>` : ''}<form class="panel narrow" method="post" action="/login">${hidden('csrf', csrf)}<div class="field"><label for="username">아이디</label><input id="username" name="username" autocomplete="username" required maxlength="80"></div><div class="field"><label for="password">비밀번호</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="128"></div><button type="submit">로그인</button><p class="muted">제공받은 합성 테스트 계정으로 로그인해 주세요.</p></form>`;
}

export function applicationForm(csrf: string, variant: Variant, values: Values, errors: Record<string, string> = {}, formToken = ''): string {
  const prefix = variant === 'decorations' ? `entry-${randomBytes(5).toString('hex')}-` : '';
  const id = (name: string) => prefix + name;
  const attrs = (name: string, hint = false) => {
    const descriptions = [...(hint ? [`${id(name)}-hint`] : []), ...(errors[name] ? [`${id(name)}-error`] : [])];
    return `${errors[name] ? ' aria-invalid="true"' : ''}${descriptions.length ? ` aria-describedby="${descriptions.join(' ')}"` : ''}`;
  };
  const error = (name: string) => errors[name] ? `<p class="field-error" id="${id(name)}-error">${escape(errors[name])}</p>` : '';
  return `<div class="intro"><h1>구매 혜택 신청</h1><p>주문 정보를 입력하고 안내를 확인해 주세요. 다음 화면에서 다시 검토할 수 있습니다.</p></div>
  <ol class="stepbar" aria-label="신청 단계"><li class="on"><b>1</b> 신청서 작성</li><li><b>2</b> 내용 검토</li><li><b>3</b> 직접 제출·접수번호 확인</li></ol>
  <table class="svc"><caption>서비스 정보</caption><tbody><tr><th scope="row">서비스명</th><td>구매 혜택 신청 (시연)</td><th scope="row">처리 부서</th><td>온담 혜택 시연팀</td></tr><tr><th scope="row">신청 방법</th><td>온라인 신청서 작성 후 검토·제출</td><th scope="row">결과 확인</th><td>접수 내역 메뉴</td></tr><tr><th scope="row">구비 서류</th><td>없음 (합성 주문 정보만 입력)</td><th scope="row">수수료</th><td>없음</td></tr></tbody></table>
  <div class="apply-layout"><div class="apply-main">
  ${Object.keys(errors).length ? `<section role="alert" class="error"><h2>입력 내용을 확인해 주세요</h2><ul>${Object.entries(errors).map(([key, text]) => `<li>${key === 'form' ? escape(text) : `<a href="#${id(key)}">${escape(text)}</a>`}</li>`).join('')}</ul></section>` : ''}
  <form class="panel" method="post" action="/apply">${hidden('csrf', csrf)}${hidden('formToken', formToken)}<fieldset><legend>구매 정보 <span class="muted">모두 필수 입력</span></legend>
  <div class="field"><label for="${id('orderNumber')}">주문번호</label><input id="${id('orderNumber')}" name="orderNumber" value="${escape(values.orderNumber)}" required maxlength="80" autocomplete="off" spellcheck="false"${attrs('orderNumber', true)}><p class="hint" id="${id('orderNumber')}-hint">시연 주문 예: FLECTO-2026-001</p>${error('orderNumber')}</div>
  <div class="field"><label for="${id('purchaseDate')}">구매일</label><input id="${id('purchaseDate')}" name="purchaseDate" type="date" value="${escape(values.purchaseDate)}" required${attrs('purchaseDate', true)}><p class="hint" id="${id('purchaseDate')}-hint">시연 구매일: 2026년 9월 1일</p>${error('purchaseDate')}</div>
  <div class="field"><label for="${id('category')}">상품분류</label><select id="${id('category')}" name="category" required${attrs('category')}><option value="">선택해 주세요</option>${categories.map(c => `<option value="${c}"${values.category === c ? ' selected' : ''}>${c}</option>`).join('')}</select>${error('category')}</div>
  ${variant === 'required' ? `<div class="field"><label for="${id('contactMethod')}">안내 수신 방법</label><select id="${id('contactMethod')}" name="contactMethod" required${attrs('contactMethod')}><option value="">선택해 주세요</option>${contactMethods.map(c => `<option value="${c}"${values.contactMethod === c ? ' selected' : ''}>${c}</option>`).join('')}</select>${error('contactMethod')}</div>` : ''}</fieldset>
  ${notice(variant)}<div class="consent"><input id="${id('consent')}" name="consent" type="checkbox" value="yes" required${values.consent ? ' checked' : ''}${attrs('consent')}><label for="${id('consent')}">위 신청 조건과 주문 정보 저장에 동의합니다. (필수)</label></div>${error('consent')}<div class="actions"><button type="submit">신청 내용 확인</button><a href="/">다음에 신청하기</a></div></form>
  ${variant === 'duplicate-form' ? `<aside class="panel secondary"><h2>신청 방법이 궁금하신가요?</h2><p>이용 안내에서 신청 절차를 확인할 수 있습니다.</p><form action="/guide" method="get"><button class="secondary-button" type="submit">신청 내용 확인</button></form></aside>` : ''}</div>
  <div class="apply-rail"><table class="rail-table"><caption>최근 안내</caption><thead><tr><th scope="col">제목</th><th scope="col">게시일</th></tr></thead><tbody><tr><td><a href="/guide">[시연] 합성 주문번호 사용 범위</a></td><td>09.01</td></tr><tr><td><a href="/guide">[시연] 접수 여부 확인 방법</a></td><td>09.08</td></tr><tr><td><a href="/stores">[시연] 매장 운영시간 안내</a></td><td>09.15</td></tr><tr><td><a href="/history">[시연] 접수 내역 조회 화면</a></td><td>09.22</td></tr></tbody></table>
  <table class="rail-table"><caption>처리 단계 안내</caption><thead><tr><th scope="col">단계</th><th scope="col">내용</th></tr></thead><tbody><tr><td>작성</td><td>필수 항목 입력·조건 동의</td></tr><tr><td>검토</td><td>입력 내용 다시 확인</td></tr><tr><td>제출</td><td>본인이 직접 제출</td></tr><tr><td>확인</td><td>접수번호 발급</td></tr></tbody></table>
  <table class="rail-table"><caption>입력 항목 형식</caption><tbody><tr><th scope="row">주문번호</th><td>영문·숫자·하이픈</td></tr><tr><th scope="row">구매일</th><td>연-월-일</td></tr><tr><th scope="row">상품분류</th><td>목록에서 선택</td></tr></tbody></table></div></div>`;
}

export function details(values: Values): string {
  return `<dl class="details"><div><dt>주문번호</dt><dd>${escape(values.orderNumber)}</dd></div><div><dt>구매일</dt><dd>${escape(values.purchaseDate)}</dd></div><div><dt>상품분류</dt><dd>${escape(values.category)}</dd></div>${values.contactMethod ? `<div><dt>안내 수신 방법</dt><dd>${escape(values.contactMethod)}</dd></div>` : ''}<div><dt>필수 동의</dt><dd>${values.consent ? '동의함' : '동의하지 않음'}</dd></div></dl>`;
}

export const css = `
:root{font-family:"Apple SD Gothic Neo","Malgun Gothic",system-ui,sans-serif;color:#222b36;background:#eef1f5;font-size:14px;line-height:1.5;--navy:#1d3a6e;--blue:#1f4fa8;--line:#cfd6e0;--muted:#5a6573}
*{box-sizing:border-box}body{margin:0;display:grid;grid-template-columns:minmax(12px,1fr) 208px minmax(0,1100px) minmax(12px,1fr);grid-template-areas:"h h h h" ". a m ." "f f f f";column-gap:14px;min-width:0}
a{color:var(--blue);text-underline-offset:3px}button,input,select{font:inherit}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #c75c00;outline-offset:2px}
button{border:1px solid var(--navy);border-radius:3px;background:var(--navy);color:#fff;padding:6px 16px;min-height:34px;font-size:14px;font-weight:700;cursor:pointer}button:hover{background:#142b55}
header{grid-area:h;background:#fff;border-bottom:1px solid var(--line)}
.util{background:#f4f6f9;border-bottom:1px solid #dde2ea;font-size:12px;color:var(--muted)}.util-inner,.header-inner,nav,.gnb-sub-inner{max-width:1336px;margin:auto;padding:0 16px}.util-inner{display:flex;align-items:center;gap:12px;min-height:30px;flex-wrap:wrap}.demo-badge{background:#b3261e;color:#fff;font-weight:700;padding:1px 7px;border-radius:2px;font-size:12px}.util-note{flex:1;min-width:200px}.util-links{display:flex;gap:12px}.util-links a{color:#3d4957;text-decoration:none}.util-links a:hover{text-decoration:underline}
.account{display:flex;gap:8px;align-items:center;font-size:12px}.account form{margin:0}.quiet{font-size:12px;background:#fff;border:1px solid #b8c1cd;color:#333;padding:2px 8px;min-height:24px;font-weight:500}.quiet:hover{background:#eef2f7}
.header-inner{display:flex;align-items:center;gap:18px;min-height:74px}.brand{font-size:26px;font-weight:850;text-decoration:none;color:var(--navy);letter-spacing:-1px;line-height:1.1}.brand span{display:block;font-size:11px;font-weight:500;letter-spacing:0;color:var(--muted)}.brand-sub{font-size:15px;font-weight:700;color:#344256;border-left:1px solid var(--line);padding-left:14px}.brand-sub small{font-size:10px;color:#fff;background:#6b7788;padding:0 4px;margin-left:4px;vertical-align:middle}
.head-status{margin-left:auto;width:auto;font-size:12px;border:1px solid var(--line)}.head-status caption{position:absolute;left:-9999px}.head-status th,.head-status td{padding:3px 8px;border:1px solid #e1e6ed}.head-status th{background:#f5f7fa;color:var(--muted);font-weight:600;white-space:nowrap}
nav{display:flex;gap:0;flex-wrap:wrap;background:var(--navy);max-width:none;padding-left:max(16px,calc((100% - 1304px)/2))}nav a{font-size:15px;font-weight:700;color:#fff;text-decoration:none;padding:10px 22px;border-right:1px solid #2f4d85}nav a:first-child{border-left:1px solid #2f4d85}nav a:hover{background:#2b4f8f}
.gnb-sub{background:#f8f9fb;border-top:1px solid #dde2ea;font-size:13px}.gnb-sub-inner{display:flex;flex-wrap:wrap;gap:4px 22px;padding-top:6px;padding-bottom:6px}.gnb-group{display:flex;gap:10px;align-items:center}.gnb-group b{font-size:12px;color:#fff;background:#6d7b90;padding:0 6px;border-radius:2px}.gnb-group a{color:#34414f;text-decoration:none}.gnb-group a:hover{color:var(--blue);text-decoration:underline}
.lnb{grid-area:a;align-self:start;margin-top:16px;background:#fff;border:1px solid var(--line);font-size:13px}.lnb h2{font-size:13px;margin:0;padding:8px 12px;background:#e8edf4;border-bottom:1px solid var(--line);color:var(--navy)}.lnb-list{list-style:none;margin:0;padding:4px 0}.lnb-list a{display:block;padding:5px 12px;color:#2c3845;text-decoration:none}.lnb-list a:hover{background:#f1f5fb;color:var(--blue)}.side-table{width:100%;font-size:12px;border-collapse:collapse}.side-table th,.side-table td{padding:4px 8px;border-bottom:1px solid #e6e9ee;text-align:left;vertical-align:top}.side-table th{color:var(--muted);font-weight:600;white-space:nowrap}.side-foot{font-size:11px;color:var(--muted);margin:0;padding:8px 12px;background:#fafbfc}
main{grid-area:m;min-width:0;padding:16px 0 40px;min-height:65vh}.loc{font-size:12px;color:var(--muted);margin:0 0 10px}.loc a{color:var(--muted)}.loc strong{color:#333}
.intro{border-bottom:2px solid var(--navy);padding-bottom:8px;margin-bottom:12px}h1{font-size:22px;line-height:1.35;letter-spacing:-.5px;margin:0 0 4px;color:#1b2533}h2{font-size:16px;line-height:1.4;margin:0 0 8px}p{margin:0 0 10px}.intro p{font-size:13px;color:var(--muted);margin:0}.muted{color:var(--muted);font-size:12px}
.stepbar{display:flex;list-style:none;padding:0;margin:0 0 12px;font-size:13px;border:1px solid var(--line);background:#fff}.stepbar li{flex:1;padding:7px 12px;color:var(--muted);border-right:1px solid var(--line)}.stepbar li:last-child{border-right:0}.stepbar li.on{background:var(--navy);color:#fff;font-weight:700}.stepbar b{display:inline-block;min-width:18px;text-align:center;border:1px solid currentColor;border-radius:50%;font-size:11px;margin-right:4px}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:7px 10px;overflow-wrap:anywhere}caption{text-align:left;font-size:14px;font-weight:700;margin-bottom:6px}.table-wrap{overflow-x:auto}
.svc{background:#fff;border-top:2px solid #5d6b80;margin-bottom:14px}.svc caption{font-size:13px}.svc th{background:#f4f6f9;width:96px;color:#3d4957;font-weight:600;font-size:12px}.svc td{font-size:13px}
.apply-layout{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:14px;align-items:start}.apply-main{min-width:0}.apply-rail{display:grid;gap:12px}.rail-table{background:#fff;border:1px solid var(--line);font-size:12px}.rail-table caption{font-size:13px;padding:0 0 4px}.rail-table th{background:#f4f6f9;color:var(--muted);font-weight:600;font-size:12px;padding:5px 8px}.rail-table td{padding:5px 8px}.rail-table a{color:#2c3845;text-decoration:none}.rail-table a:hover{text-decoration:underline;color:var(--blue)}
.panel{background:#fff;border:1px solid var(--line);border-radius:0;padding:16px 18px}.narrow{max-width:460px}
fieldset{padding:0;margin:0 0 12px;border:0;display:grid;grid-template-columns:1fr 1fr}legend{float:left;grid-column:1/-1;width:100%;font-size:15px;font-weight:700;padding:0 0 6px;border-bottom:2px solid var(--navy);color:#1b2533}legend span{display:inline;font-size:12px;font-weight:400;margin-left:6px}
.field{display:grid;grid-template-columns:104px minmax(0,1fr);border-bottom:1px solid var(--line);margin:0;min-width:0}.field>label{grid-row:1/span 3;background:#f4f6f9;padding:9px 10px;margin:0;font-size:14px;font-weight:700;color:#2b3542;border-right:1px solid var(--line)}.field>label::after{content:" *";color:#b3261e}.field>input,.field>select,.field>.hint,.field>.field-error{grid-column:2;margin-left:10px;margin-right:10px}.field>input,.field>select{margin-top:8px}
.panel.narrow .field{grid-template-columns:90px minmax(0,1fr)}.panel.narrow .field>label::after{content:""}
label{display:block;font-weight:700;margin-bottom:4px}input:not([type=checkbox]),select{width:100%;padding:5px 8px;min-height:34px;font-size:15px;border:1px solid #9aa5b4;border-radius:2px;background:#fff;color:#1b2533}select{padding-right:4px}input[aria-invalid=true],select[aria-invalid=true]{border:2px solid #a02121;background:#fff8f7}
.hint{font-size:12px;color:var(--muted);margin:4px 0 8px}.field-error{color:#a02121;margin:2px 0 8px;font-size:12px;font-weight:700}
.notice{background:#f7f8fa;border:1px solid var(--line);border-left:3px solid #5d6b80;padding:10px 12px;margin:0 0 10px}.notice h2{font-size:14px;margin:0 0 4px;color:#1b2533}.notice p{font-size:13px;line-height:1.6;margin:0;color:#333d49}
.consent{display:flex;gap:8px;align-items:flex-start;margin:10px 0;padding:8px 10px;border:1px solid var(--line);background:#fbfcfd}.consent input{flex:none;width:16px;height:16px;accent-color:var(--navy);margin:2px 0}.consent label{font-size:14px;font-weight:600;margin:0}
.actions{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin-top:12px;padding-top:12px;border-top:1px solid var(--line);font-size:13px}
.error{padding:10px 12px;border:1px solid #bf5151;background:#fff3f2;color:#861e1e;margin-bottom:12px;font-size:13px}.error h1,.error h2{font-size:15px}.error a{color:inherit}.error ul{margin:0;padding-left:18px}
.details{margin:8px 0 12px;border-top:2px solid #5d6b80;font-size:14px}.details>div{display:grid;grid-template-columns:130px 1fr;border-bottom:1px solid var(--line)}.details dt{background:#f4f6f9;color:#3d4957;padding:7px 10px;font-weight:600;font-size:13px}.details dd{margin:0;padding:7px 10px;font-weight:600;overflow-wrap:anywhere}
.secondary{margin-top:12px}.secondary h2{font-size:14px}.secondary p{font-size:13px}.secondary-button{color:var(--navy);background:#fff}.secondary-button:hover{background:#eef2f8}
.hero{padding:14px 18px;background:#fff;border:1px solid var(--line);border-top:3px solid var(--navy);margin-bottom:12px}.hero h1{font-size:22px}.hero p{font-size:13px;color:var(--muted)}.button{display:inline-block;text-decoration:none;background:var(--navy);color:#fff;padding:6px 16px;border-radius:3px;font-weight:700;font-size:14px}
.menu-list{list-style:none;padding:0;margin:0;background:#fff;border:1px solid var(--line);display:grid;grid-template-columns:repeat(3,1fr)}.menu-list li{padding:10px 14px;border-right:1px solid var(--line)}.menu-list li:last-child{border-right:0}.menu-list a{font-weight:700;font-size:14px}.menu-list p{margin:3px 0 0;font-size:12px;color:var(--muted)}
.success{border-top:3px solid #17734c}.receipt{font-size:20px;font-weight:750;color:#145b3e;overflow-wrap:anywhere}
.steps{padding-left:20px;font-size:14px}.steps li{margin:4px 0}address{font-style:normal;font-size:13px}.panel h2{margin-top:6px}
footer{grid-area:f;background:#2b323c;color:#c3cad4;font-size:12px;padding:14px max(16px,calc((100% - 1304px)/2)) 20px;margin-top:8px}footer strong{color:#fff}footer p{margin:4px 0}footer a{color:#dfe5ec}.foot-links{display:flex;gap:16px;flex-wrap:wrap;padding-bottom:8px;margin-bottom:8px;border-bottom:1px solid #444d59}.foot-meta{color:#98a2ae}
.skip{position:absolute;top:-100px;left:20px;background:#fff;padding:8px;z-index:10}.skip:focus{top:10px}
@media(max-width:1100px){.apply-layout{grid-template-columns:1fr}.head-status{display:none}}
@media(max-width:900px){body{grid-template-columns:12px minmax(0,1fr) 12px;grid-template-areas:"h h h" ". m ." ". a ." "f f f"}.lnb{margin-top:0}fieldset{grid-template-columns:1fr}.menu-list{grid-template-columns:1fr}.menu-list li{border-right:0;border-bottom:1px solid var(--line)}.util-note{display:none}nav a{padding:8px 12px;font-size:14px}}
`;
